version: "3.9"

services:

  app:
    build: .
    image: actility/tpxle-nit:0.0.1
    container_name: tpxle_nit_app

    volumes:
      - ./src:/opt/tpxle-nit/src
      - ./config:/opt/tpxle-nit/config
      - ./log:/opt/tpxle-nit/log
    working_dir: /opt/tpxle-nit/src

    #### FOR PRODUCTION ####
    # environment:
    #   NODE_ENV: production
    ########################

    #### FOR DEVELOPMENT ####
    environment:
      NODE_ENV: development
    entrypoint: ["tail"]
    command: ["-f","/dev/null"]
    #########################

    ports:
      - 8081:8081

  redis:
    image: redis:alpine
    container_name: tpxle_nit_redis
    volumes:
      - ./redis-data:/data
#    ports:
#      - 6379:6379
