version: "3.9"

services:

  app:
    build: .
    image: cerealf/tpxle-nit:0.0.1
    container_name: tpxle-nit-app
    volumes:
    #  - ./src:/opt/tpxle-nit/src
      - config:/opt/tpxle-nit/config
      - log:/opt/tpxle-nit/log
    working_dir: /opt/tpxle-nit/src
    domainname: "tpxle-nit-app"
    ports:
      - 80:80

    #### FOR PRODUCTION ####
    environment:
      NODE_ENV: production
    ########################

    #### FOR DEVELOPMENT ####
    # environment:
    #   NODE_ENV: development
    # entrypoint: ["tail"]
    # command: ["-f","/dev/null"]
    #########################

  redis:
    image: redis:alpine
    container_name: tpxle-nit-redis
    volumes:
      - redis-data:/data

volumes:
  config:
    driver: azure_file
    driver_opts:
      share_name: tpxle-nit-vol
      storage_account_name: tpxlestorage
  log:
    driver: azure_file
    driver_opts:
      share_name: tpxle-nit-vol
      storage_account_name: tpxlestorage
  redis-data:
    driver: azure_file
    driver_opts:
      share_name: tpxle-nit-vol
      storage_account_name: tpxlestorage
